kind: ConfigMap
apiVersion: v1
metadata:
  name: sampleconfigmap
  namespace: demo
  labels:
    app.kubernetes.io/part-of: argocd
data:
  database_url: "10.111.158.239:5432"
  database_username: admin
  database_table: postgresdb
  port: "8080"