apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend
spec:
  selector:
    matchLabels:
      app: myfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: myfrontend
    spec:
      containers:
        - name: myfrontend
          image: christianschueler404/example:frontend_v0.5
          ports:
            - containerPort: 80
          env:
          - name: REACT_APP_BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: frontendconfigmap
                key: REACT_APP_BACKEND_URL