kind: PersistentVolume
apiVersion: v1
metadata:
  name: myfrontend-pv-volume
  labels:
    type: local
    app: myfrontend
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app"